src/main/resources/webroot/custom-js/index.js

The homepage of application does not enable 'start' button, if input fields are auto-filled. 
**Files Changed:**
* index.js
Fix #21

Fix #21 - Auto-filling input fields does not enable 'start' button

---

pom.xml
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/GtfsFeedModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/db/GTFSDB.java
src/main/resources/createTables.sql

This PR depends on laidig_validator jar version 0.1.1.  For now, this laidig_validator version is cloned locally and installed, for this PR to work. 
Also creates and stores MD5 hash for the input static GTFS feed, so that the same GTFS feed is not validated again.
Fix #22

Fix #22 - Integrating laidig_validator into gtfs-realtime-validator to validate GTFS feed

---

pom.xml

* Now that we're using the Conveyal gtfs-validator intead of the Laidig fork, we can just pull the normal dependencies from the Conveyal repo using Maven.  We don't need Jitpack anymore.

Remove jitpack and use pure Maven for dependencies

---

.travis.yml

**Summary:**
We don't need to manually install the laidig/gtfs-validator for dependencies on Travis - following https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/dae76a4059dcfa4e47af75274ff2fac13f000cda, we're managing all build dependencies via pure Maven.
Travis should now pass without installing laidig/gtfs-validator artifacts

Remove Travis script to install laidig/gtfs-validator

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java

**Summary:**
Modified to correctly read the file name from given static Gtfs URL.
But, you will see an issue https://github.com/conveyal/gtfs-validator/issues/28, if your static Gtfs file does not have the optional file `calendar_dates.txt`. The conveyal code is missing to check null values for it. You can see the description about the issue mentioned in the above URL. The fix for the issue is created in PR https://github.com/conveyal/gtfs-validator/pull/29. 
Once the PR in conveyal project is fixed, you can expect the application to work as mentioned in the below **Expected behavior** section.
*  Try to run the application if you installed locally using, http://localhost:8080
*  Use different static Gtfs data links. For example, you may use below provided links to …

Fix #62 - Can't load GTFS data from a URL

---

pom.xml
src/main/java/edu/usf/cutr/gtfsrtvalidator/Main.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/GtfsRtFeedIterationString.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/db/GTFSDB.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/StopTimeSequanceValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/TimestampValidation.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/VehicleIdValidator.java
src/main/resources/jetty-logging.properties
src/main/resources/logging.properties

**Summary:**
* Remove existing dependencies on slf4j in pom.xml, as they aren't being used and may finally fix https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/76
* Change System.out.println() to use a Logger instead
* Cleanup output that doesn't provide useful feedback
* Update logging properties to point to slf4j instead (although  I'm not currently convinced that slf4j is currently being used to output the Logger statements)
FIXME (in the future):
* Filter of log levels still doesn't seem to work
* Not sure if slf4j is actually being used for the Logger
Start the project from within IntelliJ or command line, and see output on the console (and slf4j error should no longer appear)
@mohangandhiGH Can you please review and make sure I'm not breaking …

Fix #76 (hopefully) - Overhaul logging

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java

**Summary:**
This fixes an error that I'm seeing after making the changes in https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/81.
After this patch, an error with creating a combined GTFS-rt feed should no longer show up when running https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/81.  See https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/82 for details.
@mohangandhiGH Can you please review?

Fix #82 - When creating combined GTFS-rt feed set a header

---

README.md
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java

Fix #89 - Handle HTTP 301 redirects

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/GtfsRtFeedIterationModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/ViewFeedUniqueResponseCount.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java

**Summary:**
Now we store PB files to the database, only if it's not already stored in the last iteration of same PB file.
Fixes #92. 
Duplicate PB files are not stored in the database.

Fix #92 - Don't save duplicate PB feed files to local database

---

RULES.md
src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/ValidationRules.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/CheckTripId.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/LocationTypeReferenceValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/StopTimeSequanceValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/TimestampValidation.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/VehicleIdValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/combined/VehicleTripDescriptorValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/gtfs/StopLocationTypeValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/interfaces/FeedEntityValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/interfaces/GtfsFeedValidator.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/FeedMessageTest.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/feeds/TripUpdateFeedTest.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/feeds/combined/TripUpdateVehiclePositionTest.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/feeds/combined/TripUpdateVehiclePostionAlertTest.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/headerandentity/FeedHeaderTest.java

**Summary:**
* Implements new error rule for #102 - "E012 - Header timestamp should be greater than or equal to all other timestamps"
* For processing efficiency, allow for checking for more than one error/warning within the same implementation of `FeedEntityValidator` - this means passing back more than one `ErrorListHelperModel` from the `validate()` method.  This avoids us looping through the entire dataset more than once for errors/warnings that are related and that we can catch in the same pass.  For example, in `TimestampValidation` we now check if the timestamp is populated, and if the timestamps are greater than the feed header timestamp within the same loop.
@mohangandhiGH Could you please review this?  Please double-check to make sure I'm not missing any other assumption the …

Fix #102 - Add new rule E012 - "No entity timestamps can be greater than header"

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java

**Summary:**
Log validation warnings/errors for unique responses. Fixes #96. 
Only unique response PB feeds are validated and warnings/errors are stored in database for those unique feeds.

Fix #96 - Only log validation warnings/errors for unique responses

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/ValidationRules.java
src/main/resources/webroot/monitoring.html

**Summary:**
Fixes #99. 
When the hyperlink i.e., ID is clicked in Summary view, it open a new window to the relevant rule/warning description in RULES.md markdown file. 

Fix #99 - Hyperlink Summary record IDs to warning/error documentation

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java
src/main/resources/webroot/custom-js/loading.js
src/main/resources/webroot/loading.html
src/test/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeedTest.java

**Summary:**
Here are some screenshots of error messages for invalid requests. 
*  Provide an invalid static gtfs URL [http://gohart.org/google/google_transit2.zip](http://gohart.org/google/google_transit2.zip) and valid GTFS-RT feed [ http://api.tampa.onebusaway.org:8088/trip-updates]( http://api.tampa.onebusaway.org:8088/trip-updates). It displays the error as
*  Provide a valid static gtfs URL [http://gohart.org/google/google_transit.zip](http://gohart.org/google/google_transit.zip) and valid GTFS-RT feed [ http://api.tampa.onebusaway.org:8088/trip-upda]( http://api.tampa.onebusaway.org:8088/trip-upda). It displays the error as
Fixes #98. 
The application is expected to show detailed error mesage in UI.
Please make sure these boxes are checked before submitting …

Fix#98 - Show users detailed error messages in the UI

---

README.md
pom.xml
src/main/java/edu/usf/cutr/gtfsrtvalidator/Main.java

**Summary:**
* Remove old unused command line parameter tool, add Apache Commons CLI
* `-port 80`
Allow configuring port from command line like:
`java -jar target/gtfs-rt-validator-1.0-SNAPSHOT.jar -port 80`

Fix #112 - Allow setting port from command-line parameter

---

src/main/resources/webroot/index.html

**Summary:**
* Allow setting minimum update interval down to 1 second
* Tweak invalid value text
* However, it seems like this interval isn't actually being used to query the feed??  I'm opening another issue at for this at https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/130.
I can now set the minimum interval down to 1 second, and I get the message "Interval must be at least one second" if I set it less than that.
@mohangandhiGH Could you please take a look?

Fix #122 - Change minimum limit of update interval to 1 second

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java
src/main/resources/webroot/custom-js/monitoring.js

**Summary:**
Fixes #130. 
The update interval of server is set to user entered interval in welcome page.
Update interval of client is set to half the update interval of server refresh rate.

Fix #130 - Use user-provided interval to refresh GTFS-rt feed

---

RULES.md
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/OccurrenceModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/ValidationRule.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/ValidationRules.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/LocationTypeReferenceValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/StopTimeSequenceValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/VehicleIdValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/combined/CheckRouteAndTripIds.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/combined/FrequencyTypeZero.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/combined/TimestampValidation.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/combined/VehicleTripDescriptorValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/gtfs/StopLocationTypeValidator.java
src/main/resources/simplelogger.properties
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/UtilTest.java

**Summary:**
* By combining `OccurrenceModel.prefix + " " + ValidationRule.occurrenceSuffix`, a description of a particular occurrence of an error/warning can now be described.
* Prepares for showing occurence details in the UI via https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/139
* Simplify OccurrenceModel to fields that we're actually using
* Update all ValidationRules to include the suffix
* Change logging to use `OccurrenceModel.prefix + " " + ValidationRule.occurrenceSuffix`
* Add logging to rules that were missing logging
* Simplify StopTimeSequenceValidator - it was overly complex and building additional lists that aren't needed
* Refactoring for simplicity and code-cleanup
* Add missing rule description for E013 to Rules.md
Same UI.  Change …

Fix #140 - Use OccurrenceModel ValidationRule to generate occurrence summary

---

src/main/resources/webroot/custom-js/monitoring.js
src/main/resources/webroot/monitoring.html

**Summary:**
PR  #135 already handles
*  All time-stamps (internal timestamp and GTFS-rt  timestamp) should be stored in milliseconds past epoch.
*  Iteration timestamp doesn't match GTFS-rt header timestamp
In this PR, we added a tooltip for Log table header `Timestamp`.
When we hover on Log table header `Timestamp`, it will show tooltip "GTFS-rt header timestamp".

Add tooltip for Log header 'Timestamp'

---

.travis.yml

**Summary:**
*Please don't merge*
This is a work-in-progress for uploading build artifacts from Travis to Amazon S3 bucket so we can always have the most recent JAR available for download.
See #167 for details.

Fix #167 - Upload artifacts to Travis after CI builds

---

.travis.yml
src/main/resources/webroot/css/style.css
src/main/resources/webroot/custom-js/index.js
src/main/resources/webroot/index.html

**Summary:**
Fixes #148. 
For each text field, remove text field button is added that is hidden until some text is entered into text. Upon clicking on it, it clears the input text.
The application shouldn't fail if entered GTFS feed URL contains extra trailing spaces.
Screenshots:

Fix #148 - Removed extra trailing spaces in GTFS feed URL

---

src/main/resources/webroot/custom-js/monitoring.js

**Summary:**
Fixes #175 . 
Timer minutes should not exceed 60 after running the application for more than an hour.

Fix #175 - Clock doesn't display correct minutes for long running timer

---

pom.xml
src/main/java/edu/usf/cutr/gtfsrtvalidator/Main.java

**Summary:**
*  **Pom.xml** is only modified to get the latest jetty versions. It does not have any effect on this issue.
*  **Main.java** modifications ensures that web app resources are correctly accessed from packaged jar.
Fixes #181.
Now the JAR file generated by Travis and uploaded to S3 should work as expected without any web resources accessing errors.

Fix #181 - Correctly getting the web resources from packaged jar

---

.travis.yml
README.md
pom.xml

**Summary:**
@mohangandhiGH Just a heads up - I'm adding a build/patch number to our version number, so the new version is `1.0.0-SNAPSHOT` instead of `1.0.-SNAPSHOT`.

Add build number precision to version number

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/Main.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java

**Summary:**
When we use the jar file uploaded to Amazon S3 (generated by Travis build), it does not have any build folders. So the json output generated after static GTFS data is validated, cannot be packaged into jar. 
Therefore, to be independent of build folders and to access validation output, added an other web resource path for static GTFS validation json output directory '.../jar-location-directory/classes/webroot'.
Fixes #114. Related to issue #181.  
Now the static GTFS validation report loads successfully.

Fix #114 - Loading static GTFS validation report - Multiple web resources

---

pom.xml
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java
src/main/resources/webroot/custom-js/loading.js
src/main/resources/webroot/custom-js/monitoring.js

* Instead of using just the zip file name to identify a feed, this patch changes to using a URL-encoded version of the entire GTFS URL as the feed name.  This eliminates potential collisions between two feeds that have the same zip file name (e.g., google_transit.zip) but are hosted at two different URLs.
* I was getting 404 errors when trying to read the URL-encoded file name from "../webroot", so I bumped the Jetty version (and then got a ClassNotFoundException, and had to add a new "jetty-server" dependency in pom.xml), and that seemed to fix the issue.  Now the GTFS URL is encoded once internally, and then in the site Javascript it's encoded-twice to retrieve the validation report.
@mohangandhiGH Would you be willing to review this?  It should be fairly straightforward, I just want to …

Fix #134 - Use the GTFS URL as the unique file name

---

RULES.md
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/ValidationRules.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/entity/combined/TripDescriptorValidator.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/feeds/combined/TripUpdateVehiclePositionTest.java

~~**Please do not merge**~~
~~WIP to address https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/201 and https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/206 via new rules E030 and E031.~~
Fixes #201, #206, #209 with new rules:
* E030 - GTFS-rt alert `trip_id` does not belong to GTFS-rt alert `route_id` in GTFS `trips.txt`
* E031 - Alert `informed_entity.route_id` does not match `informed_entity.trip.route_id`
* E032 - Alert does not have an `informed_entity`
* E033 - Alert `informed_entity` does not have any specifiers

Fix #201, 206, 209 - New rules E030, E031, E032, E033 - Alert informed_entity validation

---

src/main/resources/webroot/monitoring.html

**Summary:**
Fixes #137. 
`Last iteration` in Summary UI is hyperlinked to iteration details page. Now when we click on `Last iteration`, it should open related iteration details page.

Fix #137 - Hyperlink 'Last iteration' in Summary UI to iteration details page

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/util/GtfsUtils.java

**Summary:**
Elapsed time for each iteration doesn't seem right. The reason behind this was logging of time elapsed was in improper format. Milliseconds were displayed right next to the decimal but they have been corrected now to display after two decimal places.

Fix#196 - Elapsed time for each iteration doesn't seem right

---

src/main/resources/webroot/iteration.html

**Summary:**
Rendering HTML elements in OccurrenceModel.prefix string. Fixes #198. 
If any HTML element is added to the OccurrenceModel.prefix string, it is treated as HTML element instead of plaint text. 
Suppose, try adding `<a href='http://geojson.io/#map=15/27.995876/-82.44294'>(27.995876,-82.44294)</a>` as part of any error/warnings **OccurrenceModel.prefix** description, it will be treated as a hyperlink in error/warning summary in iteraiton.html page.

Fix #198 - Allow hyperlinking of text in occurrence summary

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java
src/main/resources/webroot/custom-js/monitoring.js

**Summary:**
Towards multiple clients with simultaneous feeds monitoring. ~~Fixes #215.~~ Fixes #214.
Multiple clients are monitored without mixing the errors/warnings.

Fix #214 - Properly separate data across simultaneous feeds

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/GtfsRtFeedModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java
src/main/resources/webroot/monitoring.html
src/test/resources/testSQLScript.sql

**Summary:**
Removed GtfsRtFeedModel.startTime
GtfsRtFeedModel.startTime is no longer persistent

Fix #218 - Remove start time

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/helper/ServiceScheduler.java
src/main/resources/webroot/custom-js/monitoring.js

**Summary:**
Multiple clients with simultaneous feed monitoring is supported now
The tool should properly separate sessions and feed validation data. There should be a single thread fetching the GTFS-rt data and generating validation results for each feed being monitored, with each client having a view of that feed data based on their session start (and end) times.

Fix #215 - Support multiple clients with simultaneous feed monitoring

---

src/main/resources/hibernate.cfg.xml

**Summary:**
Pass hsqldb property log_data as false to hibernate configuration.
Logging is disabled and SQL statement logging in script file has been stopped.

Fix #242 - Turn off sql statement

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/util/GtfsUtils.java

**Summary:**
Used thread synchronization when logging the duration.
The sum of benchmark times for all rules should be the same or less than the total time it took to process the feed.

Fix #196 - Elapsed time for each iteration doesn't seem right

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java

**Summary:**
The extra allocation of an `InputStream` is removed when reading the GTFS-rt protocol buffer message.
Behavior should be the exact same as the master branch (i.e., reading and storing GTFS-rt protobuf), just without an extra allocation of an `InputStream`.
@Suryakandukoori Could you please review and merge if everything looks good?

Fix #267 - Eliminate extra inputstream when reading protobuf

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java

* Added for HTTP request and processing, protobuf decoding, and database writes for each rule
* Also add break in between iterations to make it easier to read
Provide more granular logging in `BackgroundTask`, such as:
~~~
---------------------
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
https://gtfsrt.api.translink.com.au/Feed/SEQ gtfsRtFeedUrl.openStream() in 0.331 seconds
https://gtfsrt.api.translink.com.au/Feed/SEQ IOUtils.toByteArray(in) in 2.028 seconds
https://gtfsrt.api.translink.com.au/Feed/SEQ protobuf decode in 0.011 seconds
[pool-4-thread-1] INFO edu.usf.cutr.gtfsrtvalidator.background.BackgroundTask - 
CrossFeedDescriptorValidator - rule = 0.0 seconds, database = 0.0 seconds
VehicleValidator - rule = 0.047 seconds, …

Fix #266 - Add more time duration logging in BackgroundTask

---

RULES.md
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/ValidationRules.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/rules/StopTimeUpdateValidator.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/rules/StopTimeUpdateValidatorTest.java

* When stop_sequence is missing in the GTFS-rt feed, use the stop_sequence from the GTFS feed (based on the stop_id provided in the GTFS-rt feed) to detect out-of-sequence stop_time_updates
* Add and update tests

Fix #159 - Detect out-of-order stop_sequence when stop_sequence isn't in GTFS-rt feed

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java

**Summary:**
When monitoring the MBTA VehiclePositions and TripUpdates feeds together, the first feed iteration generates a NullPointerException.
Not generate an NPE.

Fix #253 - NPE on first feed iteration when monitoring multiple feeds

---

RULES.md
src/main/java/edu/usf/cutr/gtfsrtvalidator/util/GtfsUtils.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/ValidationRules.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/rules/HeaderValidator.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/validation/rules/TimestampValidator.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/UtilTest.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/rules/HeaderValidatorTest.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/rules/TimestampValidatorTest.java

~~**Please do not merge**~~
* Update `E038`  - Add v2.0 as a valid GTFS-rt version and update `E038` unit test
* New rule `E048` - header timestamp not populated (GTFS-rt v2.0 and higher), and unit test
* New rule `E049` - header incrementality not populated (GTFS-rt v2.0 and higher), and unit test

Fix #262 - Implement errors for GTFS-rt v2.0

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/ViewFeedMessageModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java
src/main/resources/webroot/custom-js/iteration.js
src/main/resources/webroot/custom-js/monitoring.js
src/main/resources/webroot/monitoring.html

**Summary:**
Now a link to check the feed message available in the error summary area of the feed monitoring page.
The link will open an iteration details screen which shows the latest feed message if there are no errors and the latest feed message along with errors if any.

Fix #275 - Add link on Monitoring Feeds page to view most recent feed response

---

gtfs-realtime-validator-lib/pom.xml
gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/rules/CrossFeedDescriptorValidator.java
gtfs-realtime-validator-lib/src/test/java/edu/usf/cutr/gtfsrtvalidator/lib/test/rules/CrossFeedDescriptorValidatorTest.java
gtfs-realtime-validator-webapp/pom.xml

~~**Please do not merge - work in progress**~~
**Summary:**
The same vehicle should be able to be assigned to more than one trip if the trips are part of the same block (i.e., the vehicle will serve one trip and then the next trip)
* Add unit test assertion that shows incorrect error logged for E047 (prior to this PR), as described in https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/255
* Remove BiMap and replace with another pair of HashMaps
* Add check for same vehicle serving multiple trips with the same block for E047
* Also fix error in comment that mistakenly referenced E036
* Clean up left-over references to HashBiMaps, but keep TODO comments for where new rules should be inserted

Fix #255 - E047 - Allow vehicle to be assigned to multiple trips in same block

---

gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/util/TimestampUtils.java

**Summary:**
This PR pins the Locale used for decimal formatting to Locale.US to fix #349.
mvn test now succeeds on German locale. Numbers are formatted with "." as decimal separator.

Fix #349 - Set Locale.US for TimestampUtils' mDecimalFormatLocal

---

gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/batch/BatchProcessor.java

Issue #352 
**Summary:**
Protobuf files being read by BatchProcessor are never closed.
Protobuf files opened and read by BatchProcessor will close after being read, thus removing the filesystem lock preventing deletion and other operations.
- [x ] Run the unit tests with `mvn test` to make sure you didn't break anything

Fix #352 - close protobuf files opened by batch processor

---

.travis.yml
gtfs-realtime-validator-lib/pom.xml
gtfs-realtime-validator-webapp/pom.xml

**Summary:**
The JAR file is not runnable with Java 11 as java.xml.bind is no longer part of the JRE and has to be added by the build.
In https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/312#issuecomment-473732768 you've asked if this will still work with Java 8. Yes it will. To ensure this the tests are run with both Java 8 and 11.
Additionally, I had to bump the surefire version to make the tests run on Java 11.

Add javax.xml.bind as dependencies for Java 11 compatibility

---

README.md
gtfs-realtime-validator-lib/pom.xml

As discussed previously.
Turns out that the activation jar was not needed.

Update README to reflect the compatibility with Java 9,10,11 by default

---

gtfs-realtime-validator-webapp/src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java

**Summary:**
Logs an exception when the GTFS file fails to load from disk. This covers a wide range of GTFS parsing/loading errors.
Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).
Exceptions are logged to the console. Requested as an aside in #374 by @derhuerst.

Fix #351 - Added logging for failed GTFS load from disk

---

Dockerfile

see https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/374#issuecomment-599615009
This PR adapts the Dockerfile introduced in #375: I moved the args to be provided to the `java` executable from `CMD` to `ENTRYPOINT`. This should allow me to provide additional `java` options/flags easily.
FYI: I haven't tested this locally.

Dockerfile: move java args to entrypoint

---

pom.xml

**Summary:**
Update OBA and Geotools mvn repos. Build appears to be failing due to missing Geotools dependencies - see https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/380.
Builds should succeed

fix: Update OBA and Geotools mvn repos

---

.mvn/custom-settings.xml
.mvn/maven.config

**Summary:**
This Maven configuration allows Maven to use HTTP for connection to the Conveyal Maven repo. These files can be removed when the transition to the MobilityData gtfs-validator is complete (https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/193).
Closes https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/399
Build should succeed instead of fail.

fix: Allow HTTP connnection to Conveyal Maven repo
