CUTR-at-USF/gtfs-realtime-validator

pom.xml

Added missing laidig-gtfs-validator artifacts.
Fixes #51

Fix #51 - Added Missing laidig-gtfs-validator artifacts

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

See https://github.com/blog/2111-issue-and-pull-request-templates for details.

Add Github issue and pull request templates

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/MessageLogModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/OccurrenceModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/db/GTFSDB.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/helper/DBHelper.java

**Summary:**
Fixes #65 
1.  Run the application
2.  Enter the following feeds:
*  http://api.tampa.onebusaway.org:8088/trip-updates
*  http://gohart.org/google/google_transit.zip
3.  Run the gtfs-rt feed monitoring
You should not see any errors regarding ConstraintViolation while monitoring feed

Fix #65 - ConstraintViolationException while monitoring GTFS-rt feed

---

src/test/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeedTest.java

**Summary:**
Fixes #72 
When you run the application, all  unit tests should pass.

Fix #72 - Add unit test for loading GTFS data into memory

---

pom.xml
src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/FeedMessageTest.java

* Remove unneeded OneBusAway dependencies
* Move Conveyal Maven repo above OneBusAway repo so it's preferred
* Bump log4j and slf4j versions
**Summary:**
Try to remove conflicting slf4j versions.
Hopefully this eliminates the issues that @scrudden is seeing in #76.
@scrudden Could you please give this a test and see if it resolves the issue?
@mohangandhiGH Could you please review?

Fix #76 - Cleanup pom.xml to remove slf4j conflict

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java

**Summary:**
Fixes #110. 
No null pointer exception should be seen in console while running the application.

Fix #110 - NullPointerException in BackgroundTask.java file

---

pom.xml
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java
src/main/resources/webroot/css/style.css
src/main/resources/webroot/custom-js/loading.js
src/main/resources/webroot/custom-js/monitoring.js
src/main/resources/webroot/loading.html
src/main/resources/webroot/monitoring.html

Fix #23 - Integrating gtfs-validator webapp into gtfs-realtime-validator

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java

**Summary:**
* Remove extra comments for code collapsing
* Consolidate rule validation execution

Refactor BackgroundTask

---

.travis.yml
README.md
pom.xml

**Summary:**
* ~~Run on Java 7, because that's what we have defined in pom.xml via Maven~~ Update project README and pom.xml to reflect dependency on Java 8
* Allow caching artifacts

Update Travis config

---

src/main/resources/webroot/custom-js/error.js
src/main/resources/webroot/custom-js/loading.js
src/main/resources/webroot/custom-js/monitoring.js

**Summary:**
Hard-coded client to localhost is updated to take server name from window.location.
Fixes #121.
Application is expected to run the same way as it is running before this fix.

Fix #121 - Client is hard-coded to localhost

---

.mvn/jvm.config

**Summary:**
Fix for #144 by setting project-specific mvn JVM options. 
Show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

Fix #144 - added JVM config for mvn build

---

.travis.yml

**Summary:**
As specified in https://docs.travis-ci.com/user/deployment/s3/ and https://renzo.lucioni.xyz/s3-deployment-with-travis/.

Change Travis to deploy config

---

src/main/resources/webroot/custom-js/monitoring.js

**Summary:**
Fixes #174. 
Changing toggled data should not hide Log UI errors.

Fix #174 - Turning off errors in Log UI can result in hidden records

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/SessionModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/ViewErrorLogModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/ViewErrorSummaryModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/ViewFeedIterationsCount.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/ViewFeedUniqueResponseCount.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/ViewGtfsRtFeedErrorCountModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/helper/QueryHelper.java
src/main/resources/hibernate.cfg.xml
src/main/resources/webroot/css/style.css
src/main/resources/webroot/custom-js/index.js
src/main/resources/webroot/custom-js/monitoring.js
src/main/resources/webroot/custom-js/session-monitor.js
src/main/resources/webroot/index.html
src/main/resources/webroot/monitoring.html
src/main/resources/webroot/session-monitor.html
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/queries/QueryTest.java

**Summary:**
Fixes #188.
Past sessions are shown in welcome page.

Fix #188 - Show past sessions when user visits home page

---

src/main/resources/webroot/monitoring.html

**Summary:**
Rule Id is now hyperlinked
Clicking on the rule Id opens the hyperlink to rule description.

Fix #220 - Add Hyperlink rule Id

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/util/TimestampUtils.java

**Summary:**
Timestamp utils no longer user static Dateformat and Decimal format objects
Multithreaded environment must not pose an issue to thread-safety of Dateformat and Decimal format objects

Fix #264 - TimestampUtils uses non-threadsafe classes

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/util/GtfsUtils.java
src/test/java/edu/usf/cutr/gtfsrtvalidator/test/UtilTest.java

~~**Please DO NOT merge**~~
* If a single URL contains more than one message type, then evaluate it as a combined feed
~~TODO:~~
~~* Unit tests!~~

Fix #85 - Validate combined feeds at single URL

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/api/model/GtfsRtFeedModel.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java
src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java
src/main/resources/webroot/custom-js/iteration.js
src/main/resources/webroot/custom-js/loading.js
src/main/resources/webroot/index.html
src/main/resources/webroot/monitoring.html

**Summary:**
Changed the attribute name and references to GtfsRtFeedModel.gtfsUrl to GtfsRtFeedModel.gtfsRtUrl
No change in behavior

Fix #273 - GtfsRtFeedModel.gtfsUrl is misnamed

---

src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java
src/main/resources/webroot/custom-js/iteration.js

**Summary:**
To get the iteration summary (includes plain text protobuf, GTFS-rt feed URL and properties, timestamp, etc) the API design has been made more natural
Eg:
http://localhost:8080/api/gtfs-rt-feed/iterationSummary?iterationId=8865
http://localhost:8080/api/gtfs-rt-feed/iterationErrors?iterationId=8865
No change in the behavior

Fix #216 - Review API Parameters

---

gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/model/GtfsRtFeedModel.java
gtfs-realtime-validator-webapp/src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java
gtfs-realtime-validator-webapp/src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java
gtfs-realtime-validator-webapp/src/main/resources/webroot/custom-js/index.js
gtfs-realtime-validator-webapp/src/main/resources/webroot/custom-js/monitoring.js
gtfs-realtime-validator-webapp/src/main/resources/webroot/index.html

**Summary:**
Added checkbox and relevant code to enable/disable validation of shapes.txt.
Checkbox, if checked, enables validation of shapes.txt, unchecked disables the validation.

Fix #286 - Disable shapes

---

gtfs-realtime-validator-webapp/src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java
gtfs-realtime-validator-webapp/src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsRtFeed.java
gtfs-realtime-validator-webapp/src/main/java/edu/usf/cutr/gtfsrtvalidator/background/BackgroundTask.java

Fix #322 - Use Hibernate parameter binding instead of string concatenation

---

RULES.md
gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/ValidationRules.java
gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/rules/StopTimeUpdateValidator.java

This branch is used in conjunction with the [transit-feed-quality-calculator](https://github.com/CUTR-at-USF/transit-feed-quality-calculator) to count the frequency of issue #26 on [transitfeeds.com](transitfeeds.com)

Add Rule W101 to count the frequency of issue #26

---

RULES.md
gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/ValidationRules.java
gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/rules/StopTimeUpdateValidator.java

This rule is added in StopTimeUpdateValidator.java

Add Rule W102 to check if trip_update contains only one stop_time_update

---

gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/ValidationRules.java
gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/rules/StopTimeUpdateValidator.java

W104: has uncertainty
W104_0: uncertainty = 0
W104_1: uncertainty = 1

add rules to count agencies that use stop_time_update.uncertainty

---

gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/ValidationRules.java
gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/validation/rules/StopTimeUpdateValidator.java

W104_1: trip_update has trip-level delay and not stop-level delay
W104_2: trip_update has stop-level delay and not trip-level delay
W104_3: trip_update has both trip-level delay and stop-level delay

Add rule W104_1, W104_2, W104_3

---

gtfs-realtime-validator-lib/src/main/java/edu/usf/cutr/gtfsrtvalidator/lib/Main.java

**Summary:**
The usage instruction is incorrect, it expects the parameter in camel case

docs: Update usage instruction
